import type { Listing, Review, Weekday } from '../interfaces';
import { PHOTO } from './catalogue-hosts.constant';

const WEEKEND: Weekday[] = ['SAT', 'SUN'];
const WEEKDAYS: Weekday[] = ['MON', 'TUE', 'WED', 'THU', 'FRI'];
const MOST_DAYS: Weekday[] = ['TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN'];

const SAFETY_WALK = ['Your host meets you at a public place and stays with you the whole time.', 'Wear closed shoes and carry water.', 'Keep your phone in a zipped pocket in busy streets.'];
const SAFETY_HOME = ['You are a guest in a family home. Your host meets you at a public place and walks you there.', 'Tell your host about any allergies when you book.'];
const SAFETY_DRIVE = ['Your driver holds an operating licence and the vehicle is insured for passengers.', 'Seat belts for every seat. Ask for a child seat when you book.'];
const SAFETY_OUTDOORS = ['Weather changes fast. Your host will move or cancel if it is not safe, and you get your money back.', 'Bring sun protection and more water than you think you need.'];

/**
 * The traveller catalogue. "off-langa-lunch" and "off-karoo-farm" are the two listings that are live in the
 * host app's seed (same ids, titles, prices and steps), so both sides of the demo tell one story.
 * TODO: mirrored, not imported: a feature may not import another feature. Move the shared demo data up when the API lands.
 */
export const LISTINGS: readonly Listing[] = [
  {
    id: 'off-langa-lunch',
    hostId: 'host-nomsa',
    placeSlug: 'cape-town',
    category: 'FOOD',
    title: 'Home-cooked Xhosa lunch in Langa',
    description: 'Eat lunch at my home in Langa. I cook umngqusho (samp and beans), chicken and steamed bread. We eat together and I tell you about the neighbourhood.',
    photos: [PHOTO.sharedTable, PHOTO.foodBowls, PHOTO.braai, PHOTO.capeTownAerial],
    town: 'Langa, Cape Town',
    priceCents: 60_000,
    priceUnit: 'PER_TRIP',
    durationMin: 120,
    groupMin: 1,
    groupMax: 6,
    languages: ['XH', 'EN'],
    inclusions: ['A full meal', 'Ginger beer', 'Stories about Langa'],
    steps: ['We meet at the Langa taxi rank and walk to my home.', 'I show you how I cook umngqusho and steamed bread.', 'We eat lunch together and I tell you about Langa.'],
    whatToBring: ['An empty stomach'],
    safetyNotes: SAFETY_HOME,
    meetingPoint: 'Langa taxi rank, Washington Street',
    bookingMode: 'ON_REQUEST',
    availability: { weekdays: WEEKEND, times: ['13:00'] },
    ratings: [21, 2, 0, 0, 0],
    addedAt: '2026-03-14',
  },
  {
    id: 'lst-bokaap-spice',
    hostId: 'host-fatima',
    placeSlug: 'cape-town',
    category: 'EXPERIENCE',
    title: 'Bo-Kaap spice walk and koesister tasting',
    description: 'We walk the steep streets of the Bo-Kaap, stop at the spice shop my family has used for sixty years, and end on my stoep with warm koesisters and tea.',
    photos: [PHOTO.market, PHOTO.capeCoast, PHOTO.foodTable],
    town: 'Bo-Kaap, Cape Town',
    priceCents: 28_000,
    priceUnit: 'PER_PERSON',
    durationMin: 150,
    groupMin: 1,
    groupMax: 8,
    languages: ['AF', 'EN'],
    inclusions: ['Koesisters and tea', 'A bag of masala to take home', 'A local guide'],
    steps: ['We meet outside the Bo-Kaap Museum.', 'We walk up Wale Street and I tell you who lived where.', 'We choose spices at Atlas Trading.', 'We eat koesisters on my stoep.'],
    whatToBring: ['Comfortable shoes', 'A hat'],
    safetyNotes: SAFETY_WALK,
    meetingPoint: 'Bo-Kaap Museum, 71 Wale Street',
    bookingMode: 'INSTANT',
    availability: { weekdays: MOST_DAYS, times: ['09:30', '14:00'] },
    ratings: [34, 5, 1, 0, 0],
    addedAt: '2026-05-20',
  },
  {
    id: 'lst-woodstock-bike',
    hostId: 'host-jason',
    placeSlug: 'cape-town',
    category: 'GUIDE',
    title: 'Woodstock street art by bicycle',
    description: 'Two slow hours on quiet back streets looking at the walls I and my friends painted. I bring the bikes and the stories behind each piece.',
    photos: [PHOTO.cyclists, PHOTO.capeTownAerial],
    town: 'Woodstock, Cape Town',
    priceCents: 32_000,
    priceUnit: 'PER_PERSON',
    durationMin: 120,
    groupMin: 2,
    groupMax: 6,
    languages: ['EN', 'AF'],
    inclusions: ['A bicycle and helmet', 'A cold drink', 'A local guide'],
    steps: ['We meet at the Old Biscuit Mill and fit your bike.', 'We ride the mural route through Woodstock and Salt River.', 'We stop for a cold drink at a corner cafe.'],
    whatToBring: ['Closed shoes', 'Sunscreen'],
    safetyNotes: ['We ride on quiet streets in a group and I ride at the back.', 'Helmets are included and you must wear one.'],
    meetingPoint: 'The Old Biscuit Mill, 375 Albert Road',
    bookingMode: 'ON_REQUEST',
    availability: { weekdays: WEEKEND, times: ['09:00'] },
    ratings: [0, 0, 0, 0, 0],
    addedAt: '2026-09-10',
  },
  {
    id: 'lst-cpt-airport',
    hostId: 'host-mandla',
    placeSlug: 'cape-town',
    category: 'TRANSPORT',
    title: 'Airport lift to your door in a 7-seater',
    description: 'I fetch you inside arrivals and drive you to your door anywhere in Cape Town. There is space for six people and their bags.',
    photos: [PHOTO.driving, PHOTO.airport, PHOTO.capeCoast],
    town: 'Cape Town',
    priceCents: 45_000,
    priceUnit: 'PER_TRIP',
    durationMin: 60,
    groupMin: 1,
    groupMax: 6,
    languages: ['XH', 'EN'],
    inclusions: ['Help with bags', 'Bottled water', 'Waiting time if your flight is late'],
    steps: ['I wait for you at arrivals with your name on a board.', 'I help you with your bags.', 'I drive you to your door.'],
    whatToBring: [],
    safetyNotes: SAFETY_DRIVE,
    meetingPoint: 'Cape Town International Airport, arrivals hall',
    bookingMode: 'INSTANT',
    availability: { weekdays: [], times: [] },
    ratings: [52, 6, 1, 0, 0],
    addedAt: '2026-03-02',
  },
  {
    id: 'lst-soweto-on-foot',
    hostId: 'host-siya',
    placeSlug: 'soweto',
    category: 'GUIDE',
    title: 'Soweto on foot with someone who grew up here',
    description: 'We walk Vilakazi Street and then keep going, past where the buses turn around. You will meet people I have known for thirty years.',
    photos: [PHOTO.friendsSunrise, PHOTO.restaurant, PHOTO.market],
    town: 'Orlando West, Soweto',
    priceCents: 30_000,
    priceUnit: 'PER_PERSON',
    durationMin: 180,
    groupMin: 1,
    groupMax: 8,
    languages: ['ZU', 'EN'],
    inclusions: ['A local guide', 'A cold drink', 'Stops for photos'],
    steps: ['We meet at the Hector Pieterson Memorial.', 'We walk up Vilakazi Street, past the Mandela and Tutu houses.', 'We visit a backyard studio and a spaza shop.', 'We walk back to the memorial together.'],
    whatToBring: ['Comfortable shoes', 'A hat', 'Water'],
    safetyNotes: SAFETY_WALK,
    meetingPoint: 'Hector Pieterson Memorial, Khumalo Road',
    bookingMode: 'INSTANT',
    availability: { weekdays: MOST_DAYS, times: ['09:00', '13:30'] },
    ratings: [37, 4, 0, 0, 0],
    addedAt: '2026-02-18',
  },
  {
    id: 'lst-diepkloof-kota',
    hostId: 'host-siya',
    placeSlug: 'soweto',
    category: 'FOOD',
    title: 'Kota lunch and shebeen stories in Diepkloof',
    description: 'A kota is a quarter loaf filled with everything. We order from the window I have used since school, then sit in a shebeen while the owner tells you how it stayed open in the eighties.',
    photos: [PHOTO.ribs, PHOTO.restaurant],
    town: 'Diepkloof, Soweto',
    priceCents: 22_000,
    priceUnit: 'PER_PERSON',
    durationMin: 120,
    groupMin: 2,
    groupMax: 6,
    languages: ['ZU', 'EN'],
    inclusions: ['A kota and a cold drink', 'A local guide'],
    steps: ['We meet at the Diepkloof Square taxi rank.', 'We order kotas at the window and watch them being built.', 'We eat in the shebeen and hear its story.'],
    whatToBring: ['An empty stomach'],
    safetyNotes: SAFETY_WALK,
    meetingPoint: 'Diepkloof Square, Immink Drive',
    bookingMode: 'ON_REQUEST',
    availability: { weekdays: ['FRI', 'SAT', 'SUN'], times: ['12:30'] },
    ratings: [11, 3, 0, 0, 0],
    addedAt: '2026-06-03',
  },
  {
    id: 'lst-jnb-airport',
    hostId: 'host-siya',
    placeSlug: 'soweto',
    category: 'TRANSPORT',
    title: 'O.R. Tambo airport lift with a Soweto driver',
    description: 'A clean minibus, a careful driver and no surprises on the price. I track your flight and I am inside arrivals before you are.',
    photos: [PHOTO.airport, PHOTO.driving],
    town: 'Johannesburg',
    priceCents: 55_000,
    priceUnit: 'PER_TRIP',
    durationMin: 60,
    groupMin: 1,
    groupMax: 10,
    languages: ['ZU', 'EN'],
    inclusions: ['Help with bags', 'Bottled water', 'Waiting time if your flight is late'],
    steps: ['I wait for you at arrivals with your name on a board.', 'I help you with your bags.', 'I drive you to your door in Soweto or Johannesburg.'],
    whatToBring: [],
    safetyNotes: SAFETY_DRIVE,
    meetingPoint: 'O.R. Tambo International Airport, arrivals hall',
    bookingMode: 'INSTANT',
    availability: { weekdays: [], times: [] },
    ratings: [44, 3, 1, 0, 0],
    addedAt: '2026-02-20',
  },
  {
    id: 'lst-knysna-forest',
    hostId: 'host-lwazi',
    placeSlug: 'knysna',
    category: 'GUIDE',
    title: 'Knysna forest walk with a woodcutter’s grandson',
    description: 'Three unhurried hours under yellowwoods that were old when the first ships came. I know where the loerie nests and which path the elephants used.',
    photos: [PHOTO.forestPath, PHOTO.forestBridge, PHOTO.forestCabin],
    town: 'Knysna',
    priceCents: 26_000,
    priceUnit: 'PER_PERSON',
    durationMin: 180,
    groupMin: 1,
    groupMax: 8,
    languages: ['XH', 'EN', 'AF'],
    inclusions: ['A local guide', 'Rooibos tea from a flask', 'The forest permit'],
    steps: ['We meet at the Diepwalle forest station.', 'We walk the old woodcutters’ path to the big tree.', 'We stop for tea by the stream.', 'We loop back through the fern gully.'],
    whatToBring: ['Walking shoes', 'A rain jacket', 'Water'],
    safetyNotes: SAFETY_OUTDOORS,
    meetingPoint: 'Diepwalle Forest Station, R339',
    bookingMode: 'INSTANT',
    availability: { weekdays: MOST_DAYS, times: ['08:00'] },
    ratings: [19, 2, 0, 0, 0],
    addedAt: '2026-04-22',
  },
  {
    id: 'lst-knysna-supper',
    hostId: 'host-lwazi',
    placeSlug: 'knysna',
    category: 'FOOD',
    title: 'Supper in Khayalethu above the lagoon',
    description: 'My aunt cooks, I pour, and the whole lagoon turns orange below the house. It is the best view in Knysna and nobody sells tickets to it.',
    photos: [PHOTO.plates, PHOTO.beachSunrise, PHOTO.sharedTable],
    town: 'Khayalethu, Knysna',
    priceCents: 32_000,
    priceUnit: 'PER_PERSON',
    durationMin: 150,
    groupMin: 2,
    groupMax: 8,
    languages: ['XH', 'EN'],
    inclusions: ['A three-course supper', 'A drink on arrival', 'A lift back to town'],
    steps: ['I fetch you in town at five.', 'We watch the sun go down from the stoep.', 'We eat supper with the family.', 'I drive you back to your door.'],
    whatToBring: ['A warm jacket'],
    safetyNotes: SAFETY_HOME,
    meetingPoint: 'Knysna Waterfront, main entrance',
    bookingMode: 'ON_REQUEST',
    availability: { weekdays: ['THU', 'FRI', 'SAT'], times: ['17:00'] },
    ratings: [8, 1, 0, 0, 0],
    addedAt: '2026-07-11',
  },
  {
    id: 'lst-knysna-paddle',
    hostId: 'host-lwazi',
    placeSlug: 'knysna',
    category: 'EXPERIENCE',
    title: 'Sunrise paddle on the Knysna lagoon',
    description: 'Flat water, no engines and the Heads turning gold. I bring the boats and the coffee. You bring someone who does not mind an early start.',
    photos: [PHOTO.beachSunrise, PHOTO.mistyHills],
    town: 'Knysna',
    priceCents: 35_000,
    priceUnit: 'PER_PERSON',
    durationMin: 120,
    groupMin: 2,
    groupMax: 6,
    languages: ['EN', 'AF'],
    inclusions: ['A kayak and life jacket', 'Coffee and rusks', 'A local guide'],
    steps: ['We meet at the Thesen Island slipway before sunrise.', 'We paddle towards the Heads as it gets light.', 'We drift back with coffee.'],
    whatToBring: ['Clothes that can get wet', 'A dry top for after'],
    safetyNotes: ['Life jackets are included and you must wear one.', ...SAFETY_OUTDOORS],
    meetingPoint: 'Thesen Island slipway',
    bookingMode: 'ON_REQUEST',
    availability: { weekdays: WEEKEND, times: ['05:45'] },
    ratings: [0, 0, 0, 0, 0],
    addedAt: '2026-09-05',
  },
  {
    id: 'lst-montagu-lunch',
    hostId: 'host-pieter',
    placeSlug: 'montagu',
    category: 'FOOD',
    title: 'Long farm lunch under the pepper tree',
    description: 'Lamb from next door, bread from our oven and apricots in every course. Lunch starts at one and nobody looks at a watch.',
    photos: [PHOTO.platedDish, PHOTO.breakfast, PHOTO.foodTable, PHOTO.redRoad],
    town: 'Montagu',
    priceCents: 38_000,
    priceUnit: 'PER_PERSON',
    durationMin: 180,
    groupMin: 2,
    groupMax: 10,
    languages: ['AF', 'EN'],
    inclusions: ['A four-course lunch', 'Farm wine and grape juice', 'A walk through the orchard'],
    steps: ['We meet at the farm gate and walk through the orchard.', 'We sit down under the pepper tree.', 'Lunch arrives slowly. So does coffee.'],
    whatToBring: ['A hat'],
    safetyNotes: ['Tell your host about any allergies when you book.', 'If you are driving, we serve grape juice as happily as wine.'],
    meetingPoint: 'Farm gate, 6 km out on the Koo road',
    bookingMode: 'INSTANT',
    availability: { weekdays: ['FRI', 'SAT', 'SUN'], times: ['13:00'] },
    ratings: [27, 3, 0, 0, 0],
    addedAt: '2026-05-09',
  },
  {
    id: 'lst-route62-bakkie',
    hostId: 'host-pieter',
    placeSlug: 'montagu',
    category: 'TRANSPORT',
    title: 'Route 62 back roads in a farm bakkie',
    description: 'A half day on the gravel roads the tour buses cannot use: a pass, a padstal and a farm dam you can swim in. I drive, you look.',
    photos: [PHOTO.redRoad, PHOTO.openRoad, PHOTO.loneTree],
    town: 'Montagu',
    priceCents: 120_000,
    priceUnit: 'PER_TRIP',
    durationMin: 240,
    groupMin: 1,
    groupMax: 4,
    languages: ['AF', 'EN'],
    inclusions: ['A driver who farms here', 'Padstal coffee and a roosterkoek', 'A swim if it is hot'],
    steps: ['I fetch you in Montagu.', 'We drive the Ouberg pass on gravel.', 'We stop at a padstal and a farm dam.', 'I drop you back in town.'],
    whatToBring: ['Swimming things', 'Sunscreen'],
    safetyNotes: SAFETY_DRIVE,
    meetingPoint: 'Montagu Tourism office, Bath Street',
    bookingMode: 'ON_REQUEST',
    availability: { weekdays: WEEKDAYS, times: ['08:30'] },
    ratings: [6, 1, 0, 0, 0],
    addedAt: '2026-08-01',
  },
  {
    id: 'lst-montagu-apricots',
    hostId: 'host-pieter',
    placeSlug: 'montagu',
    category: 'EXPERIENCE',
    title: 'Apricot farm morning: pick, dry and taste',
    description: 'Montagu dries most of the country’s apricots. Spend a morning in the orchard and on the drying racks, and leave with a bag you picked yourself.',
    photos: [PHOTO.farmRows, PHOTO.breakfast],
    town: 'Montagu',
    priceCents: 18_000,
    priceUnit: 'PER_PERSON',
    durationMin: 150,
    groupMin: 1,
    groupMax: 12,
    languages: ['AF', 'EN'],
    inclusions: ['A bag of fruit to take home', 'Coffee and rusks', 'A walk through the drying yard'],
    steps: ['We meet at the packing shed.', 'We pick in the orchard for an hour.', 'We lay fruit on the racks and taste last season’s.'],
    whatToBring: ['A hat', 'Closed shoes'],
    safetyNotes: SAFETY_OUTDOORS,
    meetingPoint: 'Packing shed, 6 km out on the Koo road',
    bookingMode: 'INSTANT',
    availability: { weekdays: WEEKDAYS, times: ['08:00'] },
    ratings: [0, 0, 0, 0, 0],
    addedAt: '2026-09-12',
  },
  {
    id: 'off-karoo-farm',
    hostId: 'host-koos',
    placeSlug: 'graaff-reinet',
    category: 'EXPERIENCE',
    title: 'A morning on a Karoo sheep farm',
    description: 'Ride out with me at sunrise, help move the sheep, and eat breakfast on the stoep. It is quiet out here and you can see for a hundred kilometres.',
    photos: [PHOTO.loneTree, PHOTO.farmRows, PHOTO.breakfast, PHOTO.openRoad],
    town: 'Nieu-Bethesda',
    priceCents: 50_000,
    priceUnit: 'PER_PERSON',
    durationMin: 240,
    groupMin: 1,
    groupMax: 6,
    languages: ['AF', 'EN'],
    inclusions: ['Farm breakfast', 'A ride on the bakkie', 'Coffee on the stoep'],
    steps: ['We meet at the farm gate at sunrise.', 'We ride out on the bakkie and move the sheep.', 'We eat breakfast on the stoep.'],
    whatToBring: ['A warm jacket', 'Closed shoes', 'A hat'],
    safetyNotes: SAFETY_OUTDOORS,
    meetingPoint: 'Farm gate, 12 km out on the Murraysburg road',
    bookingMode: 'ON_REQUEST',
    availability: { weekdays: [], times: ['06:00'] },
    ratings: [14, 1, 0, 0, 0],
    addedAt: '2026-04-16',
  },
  {
    id: 'lst-desolation-sunset',
    hostId: 'host-annelie',
    placeSlug: 'graaff-reinet',
    category: 'GUIDE',
    title: 'Valley of Desolation at sunset with a historian',
    description: 'Dolerite columns a hundred metres tall and the whole Camdeboo plain below them. I tell you how it was made and who crossed it, then we watch the light go.',
    photos: [PHOTO.treeSunset, PHOTO.hiker, PHOTO.openRoad],
    town: 'Graaff-Reinet',
    priceCents: 35_000,
    priceUnit: 'PER_PERSON',
    durationMin: 150,
    groupMin: 1,
    groupMax: 8,
    languages: ['AF', 'EN'],
    inclusions: ['Park entry', 'A local guide', 'Something cold at the top'],
    steps: ['I fetch you in town at four.', 'We drive up through the Camdeboo park.', 'We walk the short crag trail.', 'We watch the sunset and drive down in the dusk.'],
    whatToBring: ['A warm jacket', 'Walking shoes', 'A camera'],
    safetyNotes: SAFETY_OUTDOORS,
    meetingPoint: 'Graaff-Reinet Museum, Church Street',
    bookingMode: 'INSTANT',
    availability: { weekdays: MOST_DAYS, times: ['16:00'] },
    ratings: [22, 2, 1, 0, 0],
    addedAt: '2026-06-08',
  },
  {
    id: 'lst-karoo-stars',
    hostId: 'host-koos',
    placeSlug: 'graaff-reinet',
    category: 'EXPERIENCE',
    title: 'Karoo night sky from the farm stoep',
    description: 'No town light for sixty kilometres. A telescope, a blanket, hot chocolate and someone who can name what you are looking at.',
    photos: [PHOTO.nightSky, PHOTO.treeSunset],
    town: 'Nieu-Bethesda',
    priceCents: 22_000,
    priceUnit: 'PER_PERSON',
    durationMin: 90,
    groupMin: 2,
    groupMax: 8,
    languages: ['AF', 'EN'],
    inclusions: ['Hot chocolate', 'A blanket and a chair', 'Time at the telescope'],
    steps: ['We meet at the farm gate after dark.', 'Your eyes get used to the dark on the stoep.', 'I show you the Southern Cross, the clouds of Magellan and whatever planet is up.'],
    whatToBring: ['Your warmest jacket'],
    safetyNotes: ['The farm road is gravel. Drive slowly and watch for kudu at night.', 'If it is cloudy we move your booking or give your money back.'],
    meetingPoint: 'Farm gate, 12 km out on the Murraysburg road',
    bookingMode: 'INSTANT',
    availability: { weekdays: [], times: ['20:00'] },
    ratings: [9, 0, 0, 0, 0],
    addedAt: '2026-08-19',
  },
  {
    id: 'lst-durban-bunny',
    hostId: 'host-zanele',
    placeSlug: 'durban',
    category: 'FOOD',
    title: 'Bunny chow crawl through Grey Street',
    description: 'Three bunnies, three arguments about which is best. We walk between them through the old Indian quarter so you have room for the next one.',
    photos: [PHOTO.foodBowls, PHOTO.restaurant, PHOTO.market],
    town: 'Durban',
    priceCents: 25_000,
    priceUnit: 'PER_PERSON',
    durationMin: 150,
    groupMin: 2,
    groupMax: 8,
    languages: ['ZU', 'EN'],
    inclusions: ['Three tastings', 'A cold drink', 'A local guide'],
    steps: ['We meet at the Juma Masjid on Dr Yusuf Dadoo Street.', 'We eat a quarter mutton bunny at the first stop.', 'We walk through the Madressa Arcade.', 'We finish with a bean bunny and a vote.'],
    whatToBring: ['An empty stomach', 'Comfortable shoes'],
    safetyNotes: SAFETY_WALK,
    meetingPoint: 'Juma Masjid, Dr Yusuf Dadoo Street',
    bookingMode: 'INSTANT',
    availability: { weekdays: MOST_DAYS, times: ['11:30'] },
    ratings: [29, 6, 1, 0, 0],
    addedAt: '2026-02-25',
  },
  {
    id: 'lst-warwick-market',
    hostId: 'host-zanele',
    placeSlug: 'durban',
    category: 'GUIDE',
    title: 'Warwick Junction market walk',
    description: 'Nine markets, half a million people a day and the best muthi, beadwork and mealies in the city. My mother traded here. I will introduce you properly.',
    photos: [PHOTO.market, PHOTO.friendsSunrise],
    town: 'Durban',
    priceCents: 20_000,
    priceUnit: 'PER_PERSON',
    durationMin: 120,
    groupMin: 1,
    groupMax: 6,
    languages: ['ZU', 'EN'],
    inclusions: ['A local guide', 'A roasted mealie', 'Introductions to the traders'],
    steps: ['We meet at the Berea Station entrance.', 'We walk the herb market and the bead market.', 'We eat a mealie at the Bovine Head market.'],
    whatToBring: ['Comfortable shoes', 'Small cash if you want to buy'],
    safetyNotes: SAFETY_WALK,
    meetingPoint: 'Berea Station, Johannes Nkosi Street entrance',
    bookingMode: 'INSTANT',
    availability: { weekdays: WEEKDAYS, times: ['09:00'] },
    ratings: [17, 2, 0, 0, 0],
    addedAt: '2026-03-30',
  },
  {
    id: 'lst-durban-dawn',
    hostId: 'host-zanele',
    placeSlug: 'durban',
    category: 'EXPERIENCE',
    title: 'Dawn on the Golden Mile: swim, stretch, coffee',
    description: 'Durban belongs to its early risers. We swim between the flags at North Beach, stretch on the grass with the regulars and drink coffee while the city wakes up.',
    photos: [PHOTO.beachPalms, PHOTO.beachSunrise],
    town: 'Durban',
    priceCents: 18_000,
    priceUnit: 'PER_PERSON',
    durationMin: 90,
    groupMin: 1,
    groupMax: 8,
    languages: ['ZU', 'EN'],
    inclusions: ['Coffee', 'A towel', 'A local guide'],
    steps: ['We meet at the North Beach lifeguard tower.', 'We swim between the flags.', 'We stretch on the grass and drink coffee.'],
    whatToBring: ['Swimming things', 'Sunscreen'],
    safetyNotes: ['We only swim between the flags while lifeguards are on duty.', 'If the sea is rough we walk the promenade instead.'],
    meetingPoint: 'North Beach lifeguard tower',
    bookingMode: 'ON_REQUEST',
    availability: { weekdays: [], times: ['05:30'] },
    ratings: [0, 0, 0, 0, 0],
    addedAt: '2026-09-15',
  },
];

const review = (id: string, listingId: string, travellerName: string, travellerFrom: string, rating: number, createdAt: string, text: string): Review => ({
  id,
  listingId,
  travellerName,
  travellerFrom,
  rating,
  createdAt,
  text,
});

export const REVIEWS: readonly Review[] = [
  review('rev-01', 'off-langa-lunch', 'Hannah', 'Berlin, Germany', 5, '2026-09-06', 'The best meal of our trip and the warmest welcome. Nomsa sent us home with the bread recipe.'),
  review('rev-02', 'off-langa-lunch', 'Sipho', 'Pretoria', 5, '2026-08-23', 'I am South African and I still learned things about Langa. Go hungry.'),
  review('rev-03', 'off-langa-lunch', 'Claire', 'Lyon, France', 4, '2026-08-02', 'Lovely afternoon. The walk from the taxi rank was a nice start.'),
  review('rev-04', 'lst-bokaap-spice', 'James', 'Leeds, United Kingdom', 5, '2026-09-10', 'Fatima knows everyone on the street. The koesisters were still warm.'),
  review('rev-05', 'lst-bokaap-spice', 'Thandeka', 'Johannesburg', 5, '2026-08-29', 'Finally a Bo-Kaap walk by someone who lives there. Bought far too much masala.'),
  review('rev-06', 'lst-bokaap-spice', 'Mei', 'Singapore', 4, '2026-08-11', 'Great stories. The streets are steep, so wear proper shoes.'),
  review('rev-07', 'lst-cpt-airport', 'Oliver', 'Sydney, Australia', 5, '2026-09-12', 'Flight was two hours late and Mandla was still there with a sign and a smile.'),
  review('rev-08', 'lst-cpt-airport', 'Naledi', 'Durban', 5, '2026-09-01', 'Clean car, fair price, helped my mother with her bags.'),
  review('rev-09', 'lst-soweto-on-foot', 'Lerato', 'Cape Town', 5, '2026-09-04', 'Siya stopped every few metres to greet someone. It felt like walking with the mayor.'),
  review('rev-10', 'lst-soweto-on-foot', 'Anders', 'Oslo, Norway', 5, '2026-08-20', 'We went far past where the buses stop. The backyard studio was the highlight.'),
  review('rev-11', 'lst-soweto-on-foot', 'Priya', 'Mumbai, India', 4, '2026-08-05', 'Three hours went fast. Bring water, it gets hot.'),
  review('rev-12', 'lst-diepkloof-kota', 'Tom', 'Toronto, Canada', 5, '2026-08-30', 'I could not finish the kota and I regret nothing.'),
  review('rev-13', 'lst-jnb-airport', 'Grace', 'Nairobi, Kenya', 5, '2026-09-09', 'Tracked our flight and texted us before we landed. Very easy.'),
  review('rev-14', 'lst-knysna-forest', 'Emma', 'Amsterdam, Netherlands', 5, '2026-09-03', 'Lwazi found a loerie within ten minutes. Quiet, slow and exactly what we wanted.'),
  review('rev-15', 'lst-knysna-forest', 'Bongani', 'Gqeberha', 5, '2026-08-17', 'His grandfather’s stories made the trees feel different.'),
  review('rev-16', 'lst-knysna-supper', 'Sarah', 'Dublin, Ireland', 5, '2026-08-25', 'That view. That malva pudding. We stayed an hour longer than planned.'),
  review('rev-17', 'lst-montagu-lunch', 'Katrin', 'Munich, Germany', 5, '2026-09-07', 'Four hours at a table under a tree. Nobody wanted to leave.'),
  review('rev-18', 'lst-montagu-lunch', 'Riaan', 'Stellenbosch', 4, '2026-08-16', 'Proper farm food. Book the Sunday, it is quieter.'),
  review('rev-19', 'lst-route62-bakkie', 'Lucas', 'São Paulo, Brazil', 5, '2026-08-27', 'The farm dam swim was the best hour of our holiday.'),
  review('rev-20', 'off-karoo-farm', 'Isabel', 'Madrid, Spain', 5, '2026-09-02', 'We moved two hundred sheep before breakfast. Koos is a gentleman.'),
  review('rev-21', 'off-karoo-farm', 'Pieter', 'Bloemfontein', 5, '2026-08-13', 'My kids still talk about the bakkie ride.'),
  review('rev-22', 'lst-desolation-sunset', 'Yuki', 'Osaka, Japan', 5, '2026-09-08', 'Annelie makes geology sound like gossip. The sunset did the rest.'),
  review('rev-23', 'lst-desolation-sunset', 'Dumisani', 'East London', 4, '2026-08-21', 'Beautiful. It gets cold fast at the top, take the jacket.'),
  review('rev-24', 'lst-karoo-stars', 'Chloe', 'Cape Town', 5, '2026-09-11', 'I have never seen that many stars. The hot chocolate helped.'),
  review('rev-25', 'lst-durban-bunny', 'Aisha', 'Johannesburg', 5, '2026-09-05', 'Three bunnies is a lot of bunny. Zanele is hilarious.'),
  review('rev-26', 'lst-durban-bunny', 'Mark', 'Chicago, United States', 4, '2026-08-19', 'Spicy, messy, brilliant. Wear a dark shirt.'),
  review('rev-27', 'lst-warwick-market', 'Nomvula', 'Pietermaritzburg', 5, '2026-08-28', 'I have driven past Warwick my whole life. I needed a guide to actually see it.'),
];
