import type { CancelReason, RefundKind } from '../interfaces';
import type { EMERGENCY_NUMBERS } from './traveller-options.constant';

/** Flow 4 (trips tab, trip detail, cancel, safety sheet) and Flow 5 (rate the trip, thank you). */
export const COPY_TRIPS = {
  leaveReview: 'Leave a review',
  cancelTrip: 'Cancel trip',
  cancelRequest: 'Cancel request',
  backToTrips: 'Back to my trips',
  backToTrip: 'Back to the trip',
  list: {
    title: 'Trips',
    upcoming: 'Upcoming',
    past: 'Past',
    emptyTitle: 'Your trips show here',
    empty: 'Book a meal, a walk or a lift and you will find it here, with the time and the place to meet.',
    emptyCta: 'Find somewhere to go',
    emptyUpcoming: 'Your next booking will show here.',
    emptyPast: 'Trips you have been on will show here.',
    plans: 'Your trip plans',
    plansHint: 'Places you want to go, ready to share and book.',
  },
  detail: {
    barTitle: 'Trip',
    notFound: 'This trip is not here any more. Have a look at your other trips.',
    when: 'When',
    timeToConfirm: 'Your host will confirm the time.',
    guests: 'Guests',
    total: 'Total',
    refund: (amount: string): string => `Refund: ${amount}`,
    meet: 'Where you meet',
    host: 'Your host',
    messageHost: (firstName: string): string => `Message ${firstName} on WhatsApp`,
    hostMessage: (firstName: string, title: string, when: string): string => `Hi ${firstName}, I am booked for ${title} on ${when}.`,
    directions: 'Get directions',
    share: 'Share trip',
    shareMessage: (title: string, when: string): string => `I am going to ${title} on ${when}. Here is where I will be:`,
    reschedule: 'Ask to change the date',
    rescheduleAsked: 'You asked to change the date',
    rescheduleToast: (firstName: string): string => `We have asked ${firstName} about a new date.`,
    rescheduleBanner: (firstName: string): string => `We have asked ${firstName} about a new date. Your trip stays as it is until they answer.`,
    safety: 'Safety',
    bookAgain: 'Book again',
    waiting: (firstName: string, time?: string): string => `${time ? `${firstName} has until ${time} to answer.` : `${firstName} has not answered yet.`} Nothing has been charged.`,
    refundOnItsWay: (amount: string): string => `${amount} is on its way back to you.`,
    declined: (firstName: string): string => `${firstName} could not take this booking. Nothing was charged.`,
    noRefund: 'No money is coming back for this trip. If your host had not said yes yet, nothing was charged.',
    reviewed: 'Thank you for your review. It helps the next traveller choose.',
  },
  cancel: {
    heading: 'Why are you cancelling?',
    helper: 'Choose the reason that fits best.',
    reasons: {
      PLANS_CHANGED: 'My plans changed',
      FOUND_SOMETHING_ELSE: 'I found something else',
      WEATHER: 'The weather looks bad',
      OTHER: 'Something else',
    } satisfies Record<CancelReason, string>,
    getBack: 'What you get back',
    refund: {
      FULL: {
        title: (amount: string): string => `You get all your money back: ${amount}`,
        why: (hours: number): string => `Your trip is more than ${hours} hours away.`,
      },
      PARTIAL: {
        title: (amount: string): string => `You get ${amount} back`,
        why: (hours: number, paid: string): string => `Your trip starts in less than ${hours} hours, so not all of the ${paid} you paid comes back.`,
      },
      NONE: {
        title: (): string => 'You get no money back',
        why: (): string => 'Your trip has already started.',
      },
    } satisfies Record<RefundKind, { title: (amount: string) => string; why: (hours: number, paid: string) => string }>,
    notCharged: { title: 'Nothing was charged', why: 'Your host had not said yes yet, so there is nothing to pay back.' },
    keepTrip: 'Keep my trip',
    keepRequest: 'Keep my request',
    tripCancelled: 'Your trip is cancelled.',
    requestCancelled: 'Your request is cancelled.',
    notCancellable: { title: 'This trip cannot be cancelled', message: 'It is already finished or cancelled. Open the trip to see where it stands.' },
  },
  safety: {
    title: 'Staying safe',
    body: 'If something feels wrong, leave and call for help. These numbers work from any cellphone in South Africa.',
    numbers: { any: 'Any emergency', police: 'Police', ambulance: 'Ambulance' } satisfies Record<(typeof EMERGENCY_NUMBERS)[number]['key'], string>,
    call: (name: string, number: string): string => `${name}: call ${number}`,
    share: 'Share my trip',
    shared: 'Trip link copied. Send it to someone you trust.',
    report: 'Report a problem',
    reportMessage: (title: string, when: string): string => `I need help with my trip: ${title}, ${when}.`,
  },
  review: {
    barTitle: 'Review',
    heading: 'How was it?',
    helper: (firstName: string): string => `Your review helps ${firstName} and the next traveller.`,
    rating: {
      none: 'Tap a star to rate.',
      /** One entry per star, from one star up. */
      words: ['Not good', 'Could be better', 'It was okay', 'Really good', 'I loved it'],
      chosen: (stars: string, word: string): string => `${stars}: ${word}`,
    },
    text: 'Say it in a line (optional)',
    textHelper: 'Everyone can read this on the listing.',
    photo: 'Add a photo (optional)',
    photoChange: 'Choose another photo',
    photoChosen: (name: string): string => `Photo chosen: ${name}`,
    privateNote: (firstName: string): string => `Anything ${firstName} should know? (optional)`,
    privateHelper: (firstName: string): string => `Only ${firstName} sees this. It never shows on the listing.`,
    submit: 'Send my review',
    notYet: { title: 'You can review this trip once it is done', message: 'Reviews open when your trip has happened. Open the trip to see where it stands.' },
    already: { title: 'You have already reviewed this trip', message: 'Thank you. Each trip gets one review. Open the trip to book it again.' },
  },
  thanks: {
    title: (firstName: string): string => (firstName ? `Thank you, ${firstName}` : 'Thank you'),
    body: (hostFirstName: string): string => `Your review is in. It helps ${hostFirstName} get found by the next traveller.`,
    explore: 'Explore more',
  },
} as const;
