/** Flow 1 (home, search, results, place) and Flow 2 (listing, reviews, host profile). */
export const COPY_EXPLORE = {
  wordmark: 'Hosted',
  headline: 'Real places, real people',
  sub: 'Meals, walks, lifts and guides from the people who live there.',
  searchPill: 'Where are you going?',
  emptyTitle: 'Nothing here yet',
  empty: 'No host offers this kind of thing yet. Try another kind, or see everything.',
  seeEverything: 'See everything',
  rails: {
    nearYou: 'Near you',
    loved: 'Loved by travellers',
    justAdded: 'Just added',
    hostsIn: (place: string): string => `Hosts in ${place}`,
    places: 'Browse by place',
    seeAll: 'See all',
  },
  search: {
    title: 'Search',
    ask: 'Tell us what you are looking for',
    askExamples: ['Somewhere to eat real food in Soweto tonight', 'A slow morning near Knysna for four of us', 'What is there to do in Montagu'],
    recent: 'Recent searches',
    popular: 'Popular places',
    when: 'When',
    whenAny: 'Any day',
    who: 'Who',
    fewer: 'One fewer guest',
    more: 'One more guest',
    submit: 'Search',
    clear: 'Clear',
  },
  results: {
    title: 'Results',
    anywhere: 'Anywhere',
    anyDay: 'Any day',
    count: (count: number): string => (count === 1 ? '1 place to go' : `${count} places to go`),
    filters: 'Filters',
    filtersOn: (count: number): string => `Filters (${count})`,
    map: 'Map',
    list: 'List',
    mapPlaceholder: 'The map goes here. For now, the list shows every result.',
    emptyTitle: 'Nothing matches yet',
    empty: 'Try another place, or take away a filter.',
    clear: 'Clear filters',
    filter: {
      title: 'Filters',
      price: 'Price, up to',
      duration: 'How long, up to',
      language: 'Language spoken',
      any: 'Any',
      verifiedOnly: 'Verified hosts only',
      instantOnly: 'Book without waiting',
      apply: (count: number): string => (count === 1 ? 'Show 1 place' : `Show ${count} places`),
    },
  },
  place: {
    hosts: (place: string): string => `Hosts in ${place}`,
    emptyTitle: 'No hosts here yet',
    empty: 'We are still meeting people in this town. Try a place nearby.',
    explore: 'Explore everywhere',
  },
  listing: {
    barTitle: 'Listing',
    photoOf: (title: string, position: number): string => `Photo ${position} of ${title}`,
    photoCount: (position: number, total: number): string => `${position} of ${total}`,
    share: 'Share',
    about: 'About this',
    whatYouDo: 'What you will do',
    included: 'What is included',
    meet: 'Where you meet',
    mapPlaceholder: 'You get the exact spot and directions once you book.',
    thingsToKnow: 'Things to know',
    languages: 'Languages',
    groupSize: 'Group size',
    whatToBring: 'What to bring',
    availability: 'When you can come',
    everyDay: 'Any day, by arrangement',
    onDays: (days: string): string => `Every ${days}`,
    atTimes: (times: string): string => `Starts at ${times}`,
    cancelling: 'Cancelling',
    cancelTerms: (hours: number): string => `Cancel up to ${hours} hours before and you get all your money back. After that you get half.`,
    safety: 'Staying safe',
    meetHost: 'Meet your host',
    seeProfile: (firstName: string): string => `More about ${firstName}`,
    reviews: 'Reviews',
    showAll: (count: number): string => `Show all ${count} reviews`,
    noReviewsTitle: 'No reviews yet',
    noReviews: 'Be the first to go, then tell the next traveller how it was.',
    book: 'Book',
    request: 'Request to book',
    requestNote: 'You only pay if your host says yes.',
    addToPlan: 'Add to a trip plan',
    notFound: 'This listing is not here any more. Have a look at what else is nearby.',
    backToExplore: 'Back to Explore',
  },
  reviews: {
    title: 'Reviews',
    stars: (stars: number): string => (stars === 1 ? '1 star' : `${stars} stars`),
    from: (place: string): string => `From ${place}`,
  },
  host: {
    barTitle: 'Host',
    memberSince: (date: string): string => `Hosting since ${date}`,
    speaks: 'Speaks',
    story: (firstName: string): string => `${firstName}’s story`,
    offerings: (firstName: string): string => `What ${firstName} offers`,
    notFound: 'We could not find that host. Have a look at who else is nearby.',
  },
  plan: {
    title: 'Add to a trip plan',
    body: 'A plan is a list you can share and book from later.',
    stops: (count: number): string => (count === 1 ? '1 stop' : `${count} stops`),
    newPlan: 'Start a new plan',
    newPlanLabel: 'Name your plan',
    newPlanExample: 'Example: Garden Route December',
    create: 'Create and add',
    added: (plan: string): string => `Added to ${plan}.`,
    open: 'Open the plan',
  },
} as const;
