export const COPY_COMMON = {
  back: 'Back',
  close: 'Close',
  navLabel: 'Main',
  offline: 'You are offline. What you see is from your last visit.',
  stepOf: (current: number, total: number): string => `Step ${current} of ${total}`,
  from: (amount: string): string => `From ${amount}`,
  isNew: 'New',
  priceUnit: { PER_PERSON: 'per person', PER_TRIP: 'for the group' } as const,
  ratingLabel: (rating: string, count: number): string =>
    `Rated ${rating} out of 5 by ${count} ${count === 1 ? 'traveller' : 'travellers'}`,
  reviewCount: (count: number): string => (count === 1 ? '1 review' : `${count} reviews`),
  stars: (stars: number): string => (stars === 1 ? '1 star' : `${stars} stars`),
  hostedBy: (firstName: string): string => `Hosted by ${firstName}`,
  saved: {
    add: (title: string): string => `Save ${title}`,
    remove: (title: string): string => `Remove ${title} from saved`,
    added: 'Saved.',
    removed: 'Removed from saved.',
    signIn: 'Sign in to save listings.',
  },
  badge: { IDENTITY: 'Verified', COMMUNITY: 'Community verified' } as const,
  tierName: { REGISTERED: 'Registered host', IDENTITY: 'ID verified', COMMUNITY: 'Community verified' } as const,
  group: (min: number, max: number | null): string =>
    max === null || min === max ? `${max ?? min} people` : `${min} to ${max} people`,
  minutes: (minutes: number): string => `${minutes} minutes`,
  hours: (hours: number): string => (hours === 1 ? '1 hour' : `${hours} hours`),
} as const;

export const COPY_LISTING = {
  barTitle: 'Listing',
  photoOf: (title: string, position: number): string => `Photo ${position} of ${title}`,
  photoCount: (position: number, total: number): string => `${position} of ${total}`,
  share: 'Share',
  shareBody: 'Anyone with the link can see it. They do not need an account.',
  about: 'About this',
  whatYouDo: 'What you will do',
  included: 'What is included',
  meet: 'Where you meet',
  mapPlaceholder: 'You get the exact spot and directions once you book.',
  thingsToKnow: 'Things to know',
  languages: 'Languages',
  groupSize: 'Group size',
  whatToBring: 'What to bring',
  availability: 'When you can come',
  onRequest: 'Any day, by arrangement',
  cancelling: 'Cancelling',
  cancelTerms: (hours: number): string => `Cancel up to ${hours} hours before and you get all your money back. After that you get half.`,
  safety: 'Staying safe',
  vouched: (count: number): string => `${count} ${count === 1 ? 'local recommends' : 'locals recommend'} this`,
  reviews: 'Reviews',
  showAll: (count: number): string => `Show all ${count} reviews`,
  noReviewsTitle: 'No reviews yet',
  noReviews: 'Be the first to go, then tell the next traveller how it was.',
  book: 'Book',
} as const;
