export const COPY_COMMON = {
  back: 'Back',
  close: 'Close',
  navLabel: 'Main',
  offline: 'You are offline. What you see is from your last visit.',
  stepOf: (current: number, total: number): string => `Step ${current} of ${total}`,
  from: (amount: string): string => `From ${amount}`,
  isNew: 'New',
  priceUnit: { PER_PERSON: 'per person', PER_TRIP: 'for the group' } as const,
  ratingLabel: (rating: string, count: number): string =>
    `Rated ${rating} out of 5 by ${count} ${count === 1 ? 'traveller' : 'travellers'}`,
  reviewCount: (count: number): string => (count === 1 ? '1 review' : `${count} reviews`),
  stars: (stars: number): string => (stars === 1 ? '1 star' : `${stars} stars`),
  hostedBy: (firstName: string): string => `Hosted by ${firstName}`,
  saved: {
    add: (title: string): string => `Save ${title}`,
    remove: (title: string): string => `Remove ${title} from saved`,
    added: 'Saved.',
    removed: 'Removed from saved.',
    signIn: 'Sign in to save listings.',
  },
  badge: { IDENTITY: 'Verified', COMMUNITY: 'Community verified' } as const,
  tierName: { REGISTERED: 'Registered host', IDENTITY: 'ID verified', COMMUNITY: 'Community verified' } as const,
  group: (min: number, max: number | null): string =>
    max === null || min === max ? `${max ?? min} people` : `${min} to ${max} people`,
  minutes: (minutes: number): string => `${minutes} minutes`,
  hours: (hours: number): string => (hours === 1 ? '1 hour' : `${hours} hours`),
  guests: (count: number): string => (count === 1 ? '1 guest' : `${count} guests`),
  hosts: (count: number): string => (count === 1 ? '1 host' : `${count} hosts`),
  weekdays: { MON: 'Monday', TUE: 'Tuesday', WED: 'Wednesday', THU: 'Thursday', FRI: 'Friday', SAT: 'Saturday', SUN: 'Sunday' } as const,
  weekdayShort: { MON: 'Mon', TUE: 'Tue', WED: 'Wed', THU: 'Thu', FRI: 'Fri', SAT: 'Sat', SUN: 'Sun' } as const,
  notFoundTitle: 'We could not find that',
  continue: 'Continue',
  anyTime: 'Your host confirms a time with you',
  languageName: { EN: 'English', AF: 'Afrikaans', XH: 'isiXhosa', ZU: 'isiZulu' } as const,
  on: 'On',
  off: 'Off',
} as const;

export const COPY_EXPLORE = {
  wordmark: 'Hosted',
  headline: 'Real places, real people',
  sub: 'Meals, walks, lifts and guides from the people who live there.',
  searchPill: 'Where are you going?',
  allCategories: 'Everything',
  emptyTitle: 'Nothing here yet',
  empty: 'No host offers this kind of thing yet. Try another kind, or see everything.',
  seeEverything: 'See everything',
  rails: {
    nearYou: 'Near you',
    loved: 'Loved by travellers',
    justAdded: 'Just added',
    hostsIn: (place: string): string => `Hosts in ${place}`,
    places: 'Browse by place',
    seeAll: 'See all',
  },
  search: {
    title: 'Search',
    ask: 'Tell us what you are looking for',
    askExamples: ['Somewhere to eat real food in Soweto', 'A slow morning near Knysna for four of us', 'What is there to do in Montagu'],
    recent: 'Recent searches',
    popular: 'Popular places',
    who: 'Who',
    fewer: 'One fewer guest',
    more: 'One more guest',
    submit: 'Search',
    clear: 'Clear',
  },
  results: {
    title: 'Results',
    anywhere: 'Anywhere',
    count: (count: number): string => (count === 1 ? '1 place to go' : `${count} places to go`),
    filters: 'Filters',
    filtersOn: (count: number): string => `Filters (${count})`,
    emptyTitle: 'Nothing matches yet',
    empty: 'Try another place, or take away a filter.',
    clear: 'Clear filters',
    sort: { recommended: 'Recommended', top_rated: 'Top rated', newest: 'Newest', price_asc: 'Price: low to high', price_desc: 'Price: high to low' } as const,
    filter: {
      title: 'Filters',
      price: 'Price, up to',
      duration: 'How long, up to',
      language: 'Language spoken',
      sort: 'Sort by',
      verifiedOnly: 'Verified hosts only',
      apply: (count: number | undefined): string => (count === undefined ? 'Show places' : count === 1 ? 'Show 1 place' : `Show ${count} places`),
    },
  },
  place: {
    hosts: (place: string): string => `Hosts in ${place}`,
    emptyTitle: 'No hosts here yet',
    empty: 'We are still meeting people in this town. Try a place nearby.',
    explore: 'Explore everywhere',
  },
} as const;

export const COPY_LISTING = {
  barTitle: 'Listing',
  photoOf: (title: string, position: number): string => `Photo ${position} of ${title}`,
  photoCount: (position: number, total: number): string => `${position} of ${total}`,
  share: 'Share',
  shareBody: 'Anyone with the link can see it. They do not need an account.',
  about: 'About this',
  whatYouDo: 'What you will do',
  included: 'What is included',
  meet: 'Where you meet',
  mapPlaceholder: 'You get the exact spot and directions once you book.',
  thingsToKnow: 'Things to know',
  languages: 'Languages',
  groupSize: 'Group size',
  whatToBring: 'What to bring',
  availability: 'When you can come',
  everyDay: 'Any day, by arrangement',
  onDays: (days: string): string => `Every ${days}`,
  atTimes: (times: string): string => `Starts at ${times}`,
  cancelling: 'Cancelling',
  cancelTerms: (hours: number): string => `Cancel up to ${hours} hours before and you get all your money back. After that you get half.`,
  safety: 'Staying safe',
  vouched: (count: number): string => `${count} ${count === 1 ? 'local recommends' : 'locals recommend'} this`,
  reviews: 'Reviews',
  showAll: (count: number): string => `Show all ${count} reviews`,
  noReviewsTitle: 'No reviews yet',
  noReviews: 'Be the first to go, then tell the next traveller how it was.',
  book: 'Book',
  request: 'Request to book',
  requestNote: 'You only pay if your host says yes.',
  addToTrip: 'Add to a trip',
  seeProfile: (firstName: string): string => `More about ${firstName}`,
} as const;

export const COPY_HOST = {
  barTitle: 'Host',
  memberSince: (date: string): string => `Hosting since ${date}`,
  speaks: 'Speaks',
  story: (firstName: string): string => `${firstName}’s story`,
  offerings: (firstName: string): string => `What ${firstName} offers`,
  noOfferings: (firstName: string): string => `${firstName} has nothing live right now.`,
} as const;

export const COPY_ACCOUNT = {
  saved: {
    title: 'Saved',
    loading: 'Loading…',
    emptyTitle: 'Nothing saved yet',
    empty: 'Tap the heart on a listing to keep it here for later.',
    explore: 'Explore listings',
  },
} as const;

/** Flow 3, screens 8 to 12b: pick a day, say who is coming, check it, pay, then booked or waiting for the host. */
export const COPY_BOOK = {
  flowTitle: 'Your booking',
  viewTrips: 'View my trips',
  summary: (when: string, guests: string): string => `${when} · ${guests}`,
  cta: {
    pay: (amount: string): string => `Pay ${amount}`,
    request: 'Request to book',
    sendRequest: 'Send my request',
    signIn: 'Sign in to continue',
  },
  facts: { when: 'When', guests: 'Guests', total: 'Total paid', meet: 'Where you meet' },
  date: {
    title: 'When would you like to come?',
    helper: 'Pick a day, then a start time.',
    helperAnyTime: 'Pick the day that suits you.',
    previousMonth: 'Previous month',
    nextMonth: 'Next month',
    today: (date: string): string => `Today, ${date}`,
    legend: 'Days with a line through them are not open.',
    timeTitle: 'Start time',
    noTimesLeft: 'Every start time for today has passed. Pick another day.',
    needDay: 'Pick a day to carry on.',
    needTime: 'Pick a start time to carry on.',
  },
  guests: {
    title: 'Who is coming?',
    label: 'Guests',
    fewer: 'One fewer guest',
    more: 'One more guest',
    limits: (group: string): string => `Your host takes ${group} at a time.`,
    flatPrice: 'This is one price for the whole group. It stays the same however many of you come.',
  },
  price: {
    perPerson: (price: string, guests: string): string => `${price} × ${guests}`,
    perTrip: 'For the group',
    serviceFee: 'Service fee',
    total: 'Total',
  },
  review: {
    title: 'Check your booking',
    requestTitle: 'Check your request',
    change: 'Change',
    changeWhen: 'Change the day or time',
    changeGuests: 'Change how many guests',
    cancelTerms: (hours: number): string => `Cancel up to ${hours} hours before you start and you get all your money back.`,
    details: {
      title: 'Your details',
      name: 'Your name',
      nameHelper: 'This is the name your host sees.',
      phone: 'Cellphone number',
      phoneHelper: 'Your host uses this to reach you on the day. If your number is from another country, start with + and your country code.',
      phonePlaceholder: '082 123 4567',
      whatsApp: 'Send me updates on WhatsApp',
      language: 'Language you like to speak',
    },
    payment: {
      title: 'How you want to pay',
      methods: {
        CARD: { title: 'Card', description: 'Visa or Mastercard, credit or debit.' },
        INSTANT_EFT: { title: 'Instant EFT', description: 'Pay straight from your bank account.' },
        QR: { title: 'SnapScan or Zapper', description: 'Scan a code with the app on your phone.' },
        WALLET: { title: 'Apple Pay or Google Pay', description: 'Use the card saved on your phone.' },
      },
    },
    requestNote: 'You are only charged if your host says yes.',
    signInNote: 'Sign in before you pay, so the booking is yours. What you have filled in stays on this phone.',
    errors: {
      name: 'We need your name. Type it so your host knows who is coming.',
      phone: 'That number does not look right. Check it, and start with + and your country code if it is from another country.',
      method: 'You have not chosen how to pay. Pick one of these to carry on.',
    },
  },
  pay: {
    title: 'Pay for your booking',
    requestTitle: 'Send your request',
    demo: 'This is a demo, so no money moves. We never keep your payment details.',
    onRequestCard: 'Your card is only charged if your host says yes. Nothing is taken today.',
    card: {
      number: 'Card number',
      numberPlaceholder: '1234 5678 9012 3456',
      expiry: 'Expiry date',
      expiryPlaceholder: 'MM/YY',
      cvv: 'CVV',
      cvvHelper: (digits: number): string => `The ${digits} numbers on the back of your card.`,
      name: 'Name on card',
    },
    next: {
      INSTANT: {
        INSTANT_EFT: 'Next, you pick your bank and approve the payment in your banking app.',
        QR: 'Next, we show you a code. Scan it with SnapScan or Zapper to pay.',
        WALLET: 'Next, your phone asks you to approve the payment with your face, your finger or your PIN.',
      },
      ON_REQUEST: {
        INSTANT_EFT: 'Nothing is taken today. If your host says yes, you pick your bank and approve the payment in your banking app.',
        QR: 'Nothing is taken today. If your host says yes, we send you a code to scan with SnapScan or Zapper.',
        WALLET: 'Nothing is taken today. If your host says yes, your phone asks you to approve the payment.',
      },
    },
    another: 'Pay another way',
    working: 'Working on it',
    processing: {
      title: 'Taking your payment',
      requestTitle: (host: string): string => `Sending your request to ${host}`,
      body: 'This takes a few seconds. Please keep this screen open.',
    },
    errors: {
      number: (digits: number): string => `That card number is too short. Type all ${digits} numbers from the front of your card.`,
      expiry: 'That date does not look right. Type the month and year your card ends, like 08/30.',
      cvv: (digits: number): string => `We need your CVV. Type the ${digits} numbers on the back of your card.`,
      name: 'We need the name on your card. Type it the way it is printed.',
    },
    failure: {
      DECLINED: 'Your bank said no to this card, so nothing was charged. Check the card number, or pay another way.',
      OFFLINE: 'You are offline, so nothing was charged. Connect to the internet and try again.',
      SIGNED_OUT: 'Your sign-in has ended, so nothing was charged. Sign in again and try once more.',
      UNKNOWN: 'We could not finish your booking, so nothing was charged. Go back, check your booking and try again.',
    },
  },
  confirmed: {
    title: 'You are booked',
    banner: (amount: string, host: string): string => `You paid ${amount}. ${host} knows you are coming.`,
    whatsApp: (host: string): string => `Message ${host} on WhatsApp`,
    whatsAppMessage: (host: string, title: string, when: string): string => `Hi ${host}, I booked ${title} for ${when}. See you there.`,
    calendar: 'Add to calendar',
    calendarNote: (hostedBy: string, guests: string): string => `${hostedBy}. ${guests}.`,
    share: 'Share trip with someone',
    shareMessage: (title: string, when: string): string => `I booked ${title} for ${when}. Here are the details:`,
  },
  requested: {
    title: (host: string): string => `Your request is with ${host}`,
    helper: 'We will tell you as soon as you have an answer.',
    deadline: (host: string, duration: string): string => `${host} has ${duration} to answer.`,
    until: (time: string): string => `That is until ${time}.`,
    noAnswerTitle: 'If there is no answer in time',
    noAnswer: 'We let your request go and you pay nothing. You are free to book something else.',
    notChargedTitle: 'Nothing has been charged yet',
    notCharged: (amount: string, host: string): string => `You only pay ${amount} if ${host} says yes.`,
    explore: 'Keep exploring',
  },
  notice: {
    schedule: { title: 'Pick a day first', message: 'You have not picked a day and time yet, or the one you picked has passed. Pick one to carry on.', backLabel: 'Pick a day' },
    details: { title: 'Your booking is not ready yet', message: 'We need a few more details before you can pay. Go back and check your booking.', backLabel: 'Check my booking' },
    changed: { title: 'This booking has changed', message: 'What you were looking for is out of date. Open the booking to see where it stands now.', backLabel: 'Open the booking' },
  },
} as const;

export const COPY_TRIP = {
  bookStop: 'Book this stop',
  booked: 'Booked. See the booking',
} as const;
