import type { BookingMode, PaymentMethod } from '../interfaces';

/** Flow 3, screens 8 to 12b: pick a day, say who is coming, check it, pay, then booked or waiting for the host. */
export const COPY_BOOK = {
  flowTitle: 'Your booking',
  viewTrips: 'View my trips',
  summary: (when: string, guests: string): string => `${when} · ${guests}`,
  cta: {
    pay: (amount: string): string => `Pay ${amount}`,
    request: 'Request to book',
    sendRequest: 'Send my request',
  },
  facts: {
    when: 'When',
    guests: 'Guests',
    total: 'Total paid',
    meet: 'Where you meet',
  },
  date: {
    title: 'When would you like to come?',
    helper: 'Pick a day, then a start time.',
    helperAnyTime: 'Pick the day that suits you.',
    previousMonth: 'Previous month',
    nextMonth: 'Next month',
    today: (date: string): string => `Today, ${date}`,
    legend: 'Days with a line through them are not open.',
    timeTitle: 'Start time',
    noTimesLeft: 'Every start time for today has passed. Pick another day.',
    needDay: 'Pick a day to carry on.',
    needTime: 'Pick a start time to carry on.',
  },
  guests: {
    title: 'Who is coming?',
    label: 'Guests',
    fewer: 'One fewer guest',
    more: 'One more guest',
    limits: (group: string): string => `Your host takes ${group} at a time.`,
    flatPrice: 'This is one price for the whole group. It stays the same however many of you come.',
  },
  price: {
    perPerson: (price: string, guests: string): string => `${price} × ${guests}`,
    perTrip: 'For the group',
    serviceFee: 'Service fee',
    total: 'Total',
    approx: (about: string): string => `That is ${about}. You always pay in rand.`,
  },
  review: {
    title: 'Check your booking',
    requestTitle: 'Check your request',
    change: 'Change',
    changeWhen: 'Change the day or time',
    changeGuests: 'Change how many guests',
    cancelTerms: (hours: number): string => `Cancel up to ${hours} hours before you start and you get all your money back.`,
    details: {
      title: 'Your details',
      name: 'Your name',
      nameHelper: 'This is the name your host sees.',
      phone: 'Cellphone number',
      phoneHelper: 'Your host uses this to reach you on the day. If your number is from another country, start with + and your country code.',
      phonePlaceholder: '082 123 4567',
      whatsApp: 'Send me updates on WhatsApp',
      language: 'Language you like to speak',
    },
    payment: {
      title: 'How you want to pay',
      methods: {
        CARD: { title: 'Card', description: 'Visa or Mastercard, credit or debit.' },
        INSTANT_EFT: { title: 'Instant EFT', description: 'Pay straight from your bank account.' },
        QR: { title: 'SnapScan or Zapper', description: 'Scan a code with the app on your phone.' },
        WALLET: { title: 'Apple Pay or Google Pay', description: 'Use the card saved on your phone.' },
      } satisfies Record<PaymentMethod, { title: string; description: string }>,
    },
    requestNote: 'You are only charged if your host says yes.',
    signInNote: 'We will ask you to sign in before you pay.',
    errors: {
      name: 'We need your name. Type it so your host knows who is coming.',
      phone: 'That number does not look right. Check it, and start with + and your country code if it is from another country.',
      method: 'You have not chosen how to pay. Pick one of these to carry on.',
    },
  },
  pay: {
    title: 'Pay for your booking',
    requestTitle: 'Send your request',
    demo: 'This is a demo, so no money moves. We never keep your payment details.',
    onRequestCard: 'Your card is only charged if your host says yes. Nothing is taken today.',
    card: {
      number: 'Card number',
      numberPlaceholder: '1234 5678 9012 3456',
      expiry: 'Expiry date',
      expiryPlaceholder: 'MM/YY',
      cvv: 'CVV',
      cvvHelper: (digits: number): string => `The ${digits} numbers on the back of your card.`,
      name: 'Name on card',
    },
    next: {
      INSTANT: {
        INSTANT_EFT: 'Next, you pick your bank and approve the payment in your banking app.',
        QR: 'Next, we show you a code. Scan it with SnapScan or Zapper to pay.',
        WALLET: 'Next, your phone asks you to approve the payment with your face, your finger or your PIN.',
      },
      ON_REQUEST: {
        INSTANT_EFT: 'Nothing is taken today. If your host says yes, you pick your bank and approve the payment in your banking app.',
        QR: 'Nothing is taken today. If your host says yes, we send you a code to scan with SnapScan or Zapper.',
        WALLET: 'Nothing is taken today. If your host says yes, your phone asks you to approve the payment.',
      },
    } satisfies Record<BookingMode, Record<Exclude<PaymentMethod, 'CARD'>, string>>,
    another: 'Pay another way',
    working: 'Working on it',
    processing: {
      title: 'Taking your payment',
      requestTitle: (host: string): string => `Sending your request to ${host}`,
      body: 'This takes a few seconds. Please keep this screen open.',
    },
    errors: {
      number: (digits: number): string => `That card number is too short. Type all ${digits} numbers from the front of your card.`,
      expiry: 'That date does not look right. Type the month and year your card ends, like 08/30.',
      cvv: (digits: number): string => `We need your CVV. Type the ${digits} numbers on the back of your card.`,
      name: 'We need the name on your card. Type it the way it is printed.',
    },
    failure: {
      DECLINED: 'Your bank said no to this card, so nothing was charged. Check the card number, or pay another way.',
      OFFLINE: 'You are offline, so nothing was charged. Connect to the internet and try again.',
      UNKNOWN: 'We could not finish your booking, so nothing was charged. Go back, check your booking and try again.',
    },
  },
  confirmed: {
    title: 'You are booked',
    banner: (amount: string, host: string): string => `You paid ${amount}. ${host} knows you are coming.`,
    whatsApp: (host: string): string => `Message ${host} on WhatsApp`,
    whatsAppMessage: (host: string, title: string, when: string): string => `Hi ${host}, I booked ${title} for ${when}. See you there.`,
    calendar: 'Add to calendar',
    calendarNote: (hostedBy: string, guests: string): string => `${hostedBy}. ${guests}.`,
    share: 'Share trip with someone',
    shareMessage: (title: string, when: string): string => `I booked ${title} for ${when}. Here are the details:`,
  },
  requested: {
    title: (host: string): string => `Your request is with ${host}`,
    helper: 'We will tell you as soon as you have an answer.',
    deadline: (host: string, duration: string): string => `${host} has ${duration} to answer.`,
    until: (time: string): string => `That is until ${time}.`,
    noAnswerTitle: 'If there is no answer in time',
    noAnswer: 'We let your request go and you pay nothing. You are free to book something else.',
    notChargedTitle: 'Nothing has been charged yet',
    notCharged: (amount: string, host: string): string => `You only pay ${amount} if ${host} says yes.`,
    explore: 'Keep exploring',
  },
  /** Shaped for TripNotice, so a screen spreads the words and adds where the button goes. */
  notice: {
    listing: { message: 'This listing is not here any more. Go back to Explore to find something else.', backLabel: 'Back to Explore' },
    schedule: { title: 'Pick a day first', message: 'You have not picked a day and time yet, or the one you picked has passed. Pick one to carry on.', backLabel: 'Pick a day' },
    details: { title: 'Your booking is not ready yet', message: 'We need a few more details before you can pay. Go back and check your booking.', backLabel: 'Check my booking' },
    trip: { message: 'This booking is not on this phone. Look in your trips to see what you have booked.' },
    changed: { title: 'This booking has changed', message: 'What you were looking for is out of date. Open the trip to see where it stands now.', backLabel: 'Open the trip' },
  },
} as const;
