import type { ListingCategory, PriceUnit, TripStatus, VerificationTier, Weekday } from '../interfaces';

/** Words used on more than one traveller screen. Warm, plain, second person. */
export const COPY_COMMON = {
  back: 'Back',
  close: 'Close',
  continue: 'Continue',
  save: 'Save',
  done: 'Done',
  on: 'On',
  off: 'Off',
  loading: 'Loading',
  navLabel: 'Main',
  stepOf: (current: number, total: number): string => `Step ${current} of ${total}`,
  notFoundTitle: 'We could not find that',
  notFound: 'That page is not here. It may have moved. Go back to Explore and carry on from there.',
  errorTitle: 'Something went wrong',
  error: 'It is not your fault and nothing was charged. Try again, or go back to Explore.',
  tryAgain: 'Try again',
  toExplore: 'Go to Explore',
  offline: 'You are offline. You can keep looking; bookings wait until you are connected.',
  categories: {
    all: 'All',
    EXPERIENCE: 'Experiences',
    FOOD: 'Food',
    GUIDE: 'Guides',
    TRANSPORT: 'Transport',
  } satisfies Record<ListingCategory | 'all', string>,
  categoryName: { EXPERIENCE: 'Experience', FOOD: 'Food', GUIDE: 'Guide', TRANSPORT: 'Transport' } satisfies Record<ListingCategory, string>,
  badge: { IDENTITY: 'Verified', COMMUNITY: 'Community verified' } satisfies Partial<Record<VerificationTier, string>>,
  tierName: { REGISTERED: 'Registered host', IDENTITY: 'ID verified', COMMUNITY: 'Community verified' } satisfies Record<VerificationTier, string>,
  priceUnit: { PER_PERSON: 'per person', PER_TRIP: 'for the group' } satisfies Record<PriceUnit, string>,
  from: (amount: string): string => `From ${amount}`,
  isNew: 'New',
  ratingLabel: (rating: string, count: number): string => `Rated ${rating} out of 5 by ${count} ${count === 1 ? 'traveller' : 'travellers'}`,
  reviewCount: (count: number): string => (count === 1 ? '1 review' : `${count} reviews`),
  hostedBy: (firstName: string): string => `Hosted by ${firstName}`,
  guests: (count: number): string => (count === 1 ? '1 guest' : `${count} guests`),
  group: (min: number, max: number): string => (min === max ? `${max} people` : `${min} to ${max} people`),
  hours: (hours: number): string => (hours === 1 ? '1 hour' : `${hours} hours`),
  minutes: (minutes: number): string => `${minutes} minutes`,
  anyTime: 'Any time. Your host confirms.',
  weekdays: { MON: 'Mon', TUE: 'Tue', WED: 'Wed', THU: 'Thu', FRI: 'Fri', SAT: 'Sat', SUN: 'Sun' } satisfies Record<Weekday, string>,
  saved: { add: (title: string): string => `Save ${title}`, remove: (title: string): string => `Remove ${title} from saved`, added: 'Saved.', removed: 'Removed from saved.' },
  tripStatus: { REQUESTED: 'Waiting for host', CONFIRMED: 'Confirmed', COMPLETED: 'Completed', CANCELLED: 'Cancelled' } satisfies Record<TripStatus, string>,
  voice: { hear: (firstName: string): string => `Hear ${firstName} describe it`, play: 'Play voice note', pause: 'Pause voice note' },
  share: {
    title: 'Share this',
    body: 'Anyone with the link can see it. They do not need an account.',
    copy: 'Copy the link',
    whatsApp: 'Send on WhatsApp',
    copied: 'Link copied.',
    failed: 'We could not copy the link. Press and hold it to copy.',
  },
  approx: (amount: string): string => `about ${amount}`,
  driveTime: (duration: string, from: string, to: string): string => `About ${duration} by car from ${from} to ${to}`,
  sameTown: 'In the same town',
} as const;
