import type { AvailabilityType, Difficulty, OfferingFieldId, OfferingKind, OfferingStatus, PriceUnit, PublishOutcome, Weekday } from '../interfaces';
import { ADULT_AGE, ALL_AGES } from './host-options.constant';

interface FieldCopy {
  label: string;
  question: string;
  example: string;
}

export const COPY_CREATE = {
  flowTitle: 'New offering',
  category: {
    title: 'What do you offer?',
    kinds: {
      experience: { title: 'Experience', description: 'A walk, a workshop, a visit, a story' },
      transport: { title: 'Transport', description: 'Airport runs, lifts and day drives' },
      guide: { title: 'Guide', description: 'Show people around your area' },
      food: { title: 'Food', description: 'A home-cooked meal or a tasting' },
      concierge: { title: 'Concierge', description: 'You know who to call and you arrange it' },
      security: { title: 'Security', description: 'Coming soon. Needs PSIRA registration.' },
    } satisfies Record<OfferingKind, { title: string; description: string }>,
  },
  voice: {
    title: 'Tell us about it',
    prompt: 'Say what you do, how long it takes, how many people, and what they will pay.',
    hold: 'Hold to describe what you offer',
    listening: 'We are writing down what you said.',
    heard: 'This is what we heard',
    right: 'Sounds right',
    again: 'Record again',
    type: 'Type it instead',
    savedOffline: 'You are offline. Your voice note is saved on your phone. We will write your listing when you are connected.',
    drafting: 'We are writing your listing.',
  },
  draft: {
    titleVoice: 'We drafted your listing',
    titleTyped: 'Check your listing',
    titleEdit: 'Change your listing',
    helper: 'Tap anything to change it.',
    add: 'Add this',
    receive: (amount: string, unit: string): string => `You will receive ${amount} ${unit} after our fee.`,
    feeLink: 'How our fee works',
    incomplete: 'Some things are still missing. Tap them to fill them in.',
    saveEdit: 'Save changes',
    saved: 'Your changes are saved.',
    group: (min: number, max: number): string => (min === max ? `${max} people` : `${min} to ${max} people`),
    seats: (seats: number): string => `${seats} seats`,
    moreSteps: (count: number): string => (count === 1 ? 'and 1 more step' : `and ${count} more steps`),
    halfDay: 'Half a day',
    fullDay: 'A full day',
    hours: (hours: number): string => (hours === 1 ? '1 hour' : `${hours} hours`),
    minutes: (minutes: number): string => `${minutes} minutes`,
  },
  fields: {
    title: { label: 'Name', question: 'What do you call it?', example: 'Example: Home-cooked lunch in Langa' },
    description: {
      label: 'About it',
      question: 'Tell travellers about it',
      example: 'Example: I cook umngqusho and chicken at my home. We eat together and I tell you about Langa.',
    },
    steps: {
      label: 'What you will do',
      question: 'What will you do together?',
      example: 'Say it in order, one step at a time. Example: We meet at the taxi rank. We walk to my home. We eat lunch.',
    },
    duration: { label: 'How long', question: 'How long does it take?', example: 'Choose the closest one.' },
    groupSize: { label: 'Group size', question: 'How many people can come?', example: 'Choose the fewest and the most you can take.' },
    price: { label: 'Price', question: 'What will they pay?', example: 'You choose your price. You can change it any time.' },
    inclusions: { label: 'What is included', question: 'What is included?', example: 'Example: Lunch, a cold drink, a walk to the market' },
    whatToBring: { label: 'What to bring', question: 'What should guests bring?', example: 'Example: Comfortable shoes, a hat, a warm jacket' },
    meetingPoint: { label: 'Where you meet', question: 'Where do you meet?', example: 'Example: Langa taxi rank, Washington Street' },
    region: { label: 'Area', question: 'Which area is this in?', example: 'Choose the area travellers would search for.' },
    languages: { label: 'Languages you speak', question: 'Which languages do you speak with guests?', example: 'Choose every language you are happy to host in.' },
    difficulty: { label: 'How active it is', question: 'How active is it?', example: 'Choose the closest one. It helps guests know if they can manage.' },
    ageSuitability: { label: 'Who can come', question: 'Who can come?', example: 'Choose the youngest guest you are happy to host.' },
    vehicle: { label: 'Your vehicle', question: 'What do you drive?', example: 'Example: Toyota Avanza' },
    dietaryNotes: {
      label: 'About the food',
      question: 'What should guests know about the food?',
      example: 'Example: No pork. I can cook vegetarian if you ask.',
    },
    areasCovered: {
      label: 'Areas you cover',
      question: 'Which areas do you cover?',
      example: 'Example: Orlando West, Vilakazi Street, Hector Pieterson Memorial',
    },
  } satisfies Record<OfferingFieldId, FieldCopy>,
  editor: {
    speak: 'Speak your answer',
    speakHint: 'Hold the button and say it. You can fix the words after.',
    orType: 'Or type it',
    heard: 'We wrote down what you said. Fix anything that is wrong.',
    answerLabel: 'Your answer',
    empty: 'This is still empty. Speak or type your answer to carry on.',
    somethingElse: 'Something else',
    minutesLabel: 'How many minutes?',
    fewest: 'Fewest people',
    most: 'Most people',
    fewer: 'One fewer',
    more: 'One more',
    priceLabel: 'Price in rand',
    priceEmpty: 'We need a price. Type how many rand they will pay.',
    unit: { PER_PERSON: 'Each person pays this', PER_TRIP: 'The whole group pays this' } satisfies Record<PriceUnit, string>,
    guide: (min: string, max: string, unit: string): string => `Hosts like you charge ${min} to ${max} ${unit}.`,
    addItem: 'Add something',
    addItemLabel: 'Something else that is included',
    addBringLabel: 'Something else to bring',
    addStep: 'Add this step',
    addStepLabel: 'The next step',
    firstStepLabel: 'The first step',
    remove: (item: string): string => `Remove ${item}`,
    difficulty: {
      EASY: { title: 'Easy', description: 'Mostly sitting or standing' },
      MODERATE: { title: 'Some walking', description: 'Walking on flat ground, with stops to rest' },
      HARD: { title: 'Hard work', description: 'Hills, long walks or heavy work' },
    } satisfies Record<Difficulty, { title: string; description: string }>,
    age: {
      title: (minAge: number): string => (minAge === ALL_AGES ? 'All ages' : minAge >= ADULT_AGE ? 'Adults only' : `From ${minAge} years old`),
      description: (minAge: number): string =>
        minAge === ALL_AGES ? 'Children are welcome' : minAge >= ADULT_AGE ? `${ADULT_AGE} and older` : `Children younger than ${minAge} stay home`,
    },
    town: 'Town or area',
    townExample: 'Example: Langa, Cape Town',
    place: 'Meeting place',
    shareLocation: 'Use where I am now',
    locationSaved: 'We saved where you are. Travellers see the town, not your exact spot.',
    locationFailed: 'We could not find where you are. Type the meeting place instead.',
    vehicleLabel: 'Your vehicle',
    seatsLabel: 'Seats for passengers',
  },
  suggestions: {
    experience: ['A local guide', 'A cold drink', 'Stories about the area'],
    transport: ['Help with bags', 'Bottled water', 'Child seat if you ask'],
    guide: ['A local guide', 'Stops for photos', 'Help with the language'],
    food: ['A full meal', 'A cold drink', 'Tea or coffee'],
    concierge: ['Everything booked for you', 'I meet you there', 'Help on WhatsApp all day'],
    security: [],
  } satisfies Record<OfferingKind, string[]>,
  bringSuggestions: {
    experience: ['Comfortable shoes', 'A hat', 'Water'],
    transport: ['Your own child seat', 'A charged phone'],
    guide: ['Comfortable shoes', 'A hat', 'Water'],
    food: ['An empty stomach', 'A warm jacket in winter'],
    concierge: ['A warm jacket', 'A charged phone'],
    security: [],
  } satisfies Record<OfferingKind, string[]>,
  photos: {
    title: 'Add photos',
    label: 'Photos',
    helper: (count: number): string => `${count} photos is enough to go live.`,
    slot: (position: number): string => `Photo ${position}`,
    count: (count: number): string => (count === 1 ? '1 photo' : `${count} photos`),
    take: 'Take a photo',
    upload: 'Choose from my phone',
    remove: (position: number): string => `Remove photo ${position}`,
    data: (size: string): string => `Uploading these will use about ${size} of data.`,
    failed: 'We could not use that photo. Try another one.',
    skip: 'Skip photos',
    skipTitle: 'Skip photos for now?',
    skipBody: 'Listings with photos get booked more. You can add them later.',
    skipConfirm: 'Skip for now',
    addNow: 'Add photos now',
  },
  availability: {
    title: 'When are you available?',
    label: 'When you host',
    options: {
      ON_REQUEST: { title: 'On request', description: 'Travellers ask, you say yes or no. Good if you have a job.' },
      RECURRING: { title: 'Certain days each week', description: 'The same days every week' },
      DATES: { title: 'Specific dates', description: 'Only the days you choose' },
    } satisfies Record<AvailabilityType, { title: string; description: string }>,
    weekdays: { MON: 'Mon', TUE: 'Tue', WED: 'Wed', THU: 'Thu', FRI: 'Fri', SAT: 'Sat', SUN: 'Sun' } satisfies Record<Weekday, string>,
    chooseDays: 'Which days?',
    addDate: 'Add a date',
    removeDate: (date: string): string => `Remove ${date}`,
    needDays: 'Choose at least one day to carry on.',
    needDates: 'Add at least one date to carry on.',
  },
  preview: {
    title: 'This is what travellers see',
    english: 'We show your listing to travellers in English.',
    voiceNote: 'Travellers can also hear your voice note.',
    publish: 'Publish',
    change: 'Change something',
    hostedBy: (firstName: string): string => `Hosted by ${firstName}`,
    whatYouDo: 'What you will do',
    included: 'What is included',
    when: 'When you can come',
    onRequest: 'Ask for the day you want. Your host says yes or no.',
    everyWeek: (days: string): string => `Every ${days}`,
    meet: 'Where you meet',
    meetHost: 'Meet your host',
    thingsToKnow: 'Things to know',
    languages: 'Languages',
    vehicle: 'Vehicle',
    areas: 'Areas covered',
    groupAndAge: (group: string, age: string): string => `${group}. ${age}.`,
    cancelling: 'Cancelling',
    cancelTerms: (hours: number): string => `Cancel up to ${hours} hours before and you get all your money back.`,
    book: 'Book',
    isNew: 'New',
    photoAlt: (title: string): string => `Photo of ${title}`,
    incomplete: 'Your listing is not finished. Go back and fill in what is missing.',
  },
  published: {
    LIVE: {
      title: 'Your listing is live',
      lines: ['Travellers can find it and book it now.', 'We will message you when someone wants to book.'],
      cta: undefined,
    },
    WAITING_TO_UPLOAD: {
      title: 'Waiting to upload',
      lines: ['Your listing is saved on your phone.', 'It goes live by itself as soon as you are connected.'],
      cta: undefined,
    },
    NEEDS_ID: {
      title: 'Saved. One more step.',
      lines: ['Your listing is ready.', 'Verify your ID and it goes live.'],
      cta: 'Verify with my ID',
    },
    NEEDS_LICENCE: {
      title: 'We need your licence first',
      lines: ['Transport listings need an operating licence before they go live.', 'Send us your licence number and we will check it.'],
      cta: 'Send my licence number',
    },
  } satisfies Record<PublishOutcome, { title: string; lines: string[]; cta: string | undefined }>,
  publishedAnother: 'Add another',
  publishedList: 'Go to my offerings',
  needsIdReason: 'Verify your ID and this goes live.',
  needsLicenceReason: 'Transport listings need your operating licence before they go live.',
} as const;

export const COPY_OFFERINGS = {
  title: 'My offerings',
  add: 'Add an offering',
  emptyTitle: 'Start with one offering',
  empty: 'Tell us what you do and travellers can book you. You can just speak.',
  emptyCta: 'Create my first offering',
  addPhotos: 'Add photos',
  photosNote: 'Only finished offerings with a photo go live. Add a photo to a draft and it publishes.',
  nextSteps: {
    title: 'Your next steps',
    progress: (done: number, total: number): string => `${done} of ${total} done`,
    done: 'Done',
    verify: { title: 'Verify your ID', body: 'Travellers book people they can trust.' },
    offering: { title: 'Create your first offering', body: 'Tell us what you do. You can just speak.' },
    photos: { title: 'Add photos', body: 'Listings with photos get booked more.' },
  },
  verifyPrompt: 'Verify your ID so your offerings can go live.',
  verifyCta: 'Verify now',
  resumePrompt: 'You have a listing you did not finish.',
  resumeCta: 'Carry on',
  untitled: 'Listing with no name yet',
  status: { DRAFT: 'Draft', IN_REVIEW: 'In review', LIVE: 'Live', PAUSED: 'Paused', REJECTED: 'Rejected' } satisfies Record<OfferingStatus, string>,
  detail: {
    title: 'Offering',
    views: 'Views',
    bookings: 'Bookings',
    earned: 'Earned',
    edit: 'Edit',
    pause: 'Pause',
    resume: 'Resume',
    duplicate: 'Make a copy',
    delete: 'Delete',
    deleteTitle: 'Delete this offering?',
    deleteBody: 'Travellers will not see it any more. You cannot undo this.',
    deleteConfirm: 'Yes, delete it',
    keep: 'Keep it',
    paused: 'Paused. Travellers cannot book this now.',
    resumed: 'It is live again.',
    duplicated: 'We made a copy. It is saved as a draft.',
    deleted: 'Deleted.',
    notFound: 'We could not find that offering. Go back to your offerings.',
    backToList: 'Back to my offerings',
  },
} as const;
