import type { BookingStatus, ContactChannel, PayoutChannel, PayoutStatus, ResponseReason } from '../interfaces';

export const COPY_BOOKINGS = {
  title: 'Bookings',
  requests: 'Needs your answer',
  upcoming: 'Coming up',
  past: 'Past',
  emptyTitle: 'No bookings yet',
  empty: 'When a traveller wants to book you, it shows here. We also send you a message.',
  emptyCtaOffer: 'Create an offering',
  emptyCtaList: 'See my offerings',
  emptyRequests: 'No new requests. We will message you when someone wants to book.',
  emptyUpcoming: 'Nothing is booked yet. Bookings you accept show here.',
  emptyPast: 'Bookings you finish will show here.',
  status: {
    REQUESTED: 'Needs your answer',
    CONFIRMED: 'Confirmed',
    DECLINED: 'Declined',
    COMPLETED: 'Completed',
    CANCELLED: 'Cancelled',
  } satisfies Record<BookingStatus, string>,
  card: {
    receive: (amount: string): string => `You will receive ${amount}`,
    received: (amount: string): string => `You received ${amount}`,
    answerBy: (time: string): string => `Answer by ${time}`,
    paidInFull: 'The group has paid in full.',
    stillPaying: (paid: number, of: number): string => `The group is still paying. ${paid} of ${of} have paid.`,
    accept: 'Accept',
    decline: 'Decline',
    open: 'See booking',
  },
  detail: {
    title: 'Booking',
    when: 'When',
    who: 'Who',
    meeting: 'Where you meet',
    phone: 'Traveller phone',
    phoneHidden: 'You see the number after you accept.',
    whatsapp: 'Message on WhatsApp',
    whatsappMessage: (firstName: string): string => `Hi ${firstName}, I am your host. `,
    cancel: 'Cancel booking',
    complete: 'Mark as completed',
    accepted: 'Accepted. We told the traveller.',
    notFound: 'We could not find that booking. Go back to your bookings.',
    backToList: 'Back to my bookings',
  },
  respond: {
    declineTitle: 'Why are you declining?',
    cancelTitle: 'Why are you cancelling?',
    reasons: {
      NOT_AVAILABLE: 'I am not available',
      TOO_MANY_PEOPLE: 'Too many people',
      SOMETHING_CAME_UP: 'Something came up',
      OTHER: 'Another reason',
    } satisfies Record<ResponseReason, string>,
    ranking: 'If you cancel often, travellers see your offerings less.',
    refund: 'The traveller gets all their money back.',
    declineCta: 'Decline booking',
    cancelCta: 'Cancel booking',
    declined: 'Declined. We told the traveller.',
    cancelled: 'Cancelled. We told the traveller.',
    queued: 'Saved on your phone. We will tell the traveller when you are connected.',
  },
  completed: {
    title: 'Well done. Your money is on its way.',
    amount: (amount: string): string => `You will receive ${amount}`,
    timing: (destination: string, when: string): string => `We send it to ${destination} by ${when}.`,
    cta: 'See my earnings',
    back: 'Back to my bookings',
  },
} as const;

export const COPY_EARNINGS = {
  title: 'Earnings',
  total: 'Total earned',
  pending: 'On its way',
  paidOut: 'Paid out',
  history: 'Your bookings',
  emptyTitle: 'Your money shows here',
  empty: 'After you finish a booking, we send your money within 24 hours. You do not need a bank account.',
  emptyCta: 'See how you get paid',
  howPaid: 'How you get paid',
  feeLink: 'How our fee works',
  payoutStatus: { PENDING: 'On its way', SENT: 'Paid' } satisfies Record<PayoutStatus, string>,
  sentNotice: (amount: string, destination: string): string => `${amount} sent to ${destination}. Tap to see it.`,
  method: {
    title: 'How do you want to get paid?',
    helper: 'You do not need a bank account.',
    options: {
      CASH_SEND: { title: 'Cash send to my phone number', description: 'Withdraw at any ATM with a PIN. No bank account needed.' },
      BANK: { title: 'Bank account', description: 'Straight into your account.' },
      WALLET: { title: 'Mobile wallet', description: 'Use it for airtime, groceries and bills.' },
      CASH_PICKUP: { title: 'Cash pickup at a shop', description: 'Collect your cash at a shop near you.' },
    } satisfies Record<PayoutChannel, { title: string; description: string }>,
    saved: 'Saved. This is how we will pay you.',
  },
  details: {
    CASH_SEND: { title: 'Which number should we send cash to?', helper: 'You get an SMS with a PIN. Use it at any ATM.' },
    BANK: { title: 'Your bank details', helper: 'We only use this to pay you.' },
    WALLET: { title: 'Which wallet do you use?', helper: 'We send the money to the number on your wallet.' },
    CASH_PICKUP: { title: 'Which shop is closest to you?', helper: 'We SMS you a voucher number. Take it and your ID to the shop.' },
  } satisfies Record<PayoutChannel, { title: string; helper: string }>,
  fields: {
    phone: 'Cellphone number',
    phoneInvalid: 'That number does not look right. Type your 10 digit cellphone number.',
    bank: 'Your bank',
    account: 'Account number',
    accountInvalid: 'We need your account number. Type it to carry on.',
    choose: 'Choose one to carry on.',
  },
  payout: {
    title: 'Payout',
    sent: (amount: string, destination: string): string => `${amount} sent to ${destination}.`,
    pending: (amount: string, destination: string, when: string): string => `${amount} is on its way to ${destination}. You should have it by ${when}.`,
    collect: {
      CASH_SEND: 'Withdraw at any ATM with your PIN.',
      BANK: 'It shows in your account today.',
      WALLET: 'It is in your wallet now.',
      CASH_PICKUP: 'Collect it at your shop with your ID and the voucher number.',
    } satisfies Record<PayoutChannel, string>,
    how: 'How does this work?',
    howTitle: 'Getting your cash',
    howSteps: [
      'We SMS you a PIN when the money is sent.',
      'Go to any ATM and choose cardless or cash send.',
      'Type your cellphone number and the PIN.',
      'Take your cash. You do not need a card or a bank account.',
    ],
    forBooking: 'For this booking',
    notFound: 'We could not find that payout. Go back to your earnings.',
    backToEarnings: 'Back to my earnings',
  },
  fees: {
    title: 'How our fee works',
    lead: (percent: number): string => `We keep ${percent}% of each booking. You keep the rest.`,
    example: (price: string, fee: string, receive: string): string => `If a traveller pays ${price}, we keep ${fee} and you receive ${receive}.`,
    whyTitle: 'What the fee pays for',
    why: [
      'Finding travellers for you',
      'Taking payment safely and holding it until the day',
      'Paying you out, even with no bank account',
      'Help on WhatsApp when something goes wrong',
    ],
    promise: 'You always see what you will receive before you publish or accept.',
  },
} as const;

export const COPY_PROFILE = {
  title: 'Profile',
  verification: 'Verification',
  moreVerified: 'Get more verified',
  language: 'Language',
  contact: 'How we contact you',
  payout: 'How you get paid',
  notifications: 'Notifications',
  help: 'Get help on WhatsApp',
  signOut: 'Sign out',
  signOutOffline: 'Connect to the internet to sign out, so your changes are saved first.',
  languageScreen: {
    title: 'Choose your language',
    note: 'We are still translating the app. Your voice notes and listings already work in your language.',
    saved: 'Saved.',
  },
  notificationsScreen: {
    title: 'Notifications',
    helper: 'Choose where we tell you about bookings and payments.',
    channels: { WHATSAPP: 'WhatsApp', SMS: 'SMS', IN_APP: 'In this app' } satisfies Record<ContactChannel, string>,
    on: 'On',
    off: 'Off',
    keepOne: 'Keep at least one on so you do not miss a booking.',
  },
} as const;
